[[language]]
name = "cpp"
auto-format = true
[language-server.cmake-language-server.config]
buildDirectory="release"
[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true

[language-server.rust-analyzer]
config = {rust-analyzer ={ cargo = { buildScripts = {enable = false} } }}
